export const Command = {
    OFF : 0,
    ON: 1,

    PULSE: 2,
    SET_BRIGHTNESS: 3,
    SET_INTENSIVITY: 4,
    SET_COLOR: 5,

    SPIN_CLOCKWISE: 6,
    SPIN_COUNTERCLOCKWISE: 7,
    CHANGE_SPIN_DIRECTION: 8,
    STOP_SPIN: 9,

    TURN_ON_ANGLE: 10,

    MOVE_FORWARD: 11,
    MOVE_BACK: 12,
    TURN_LEFT: 13,
    TURN_RIGHT: 14,
    STOP_MOVING: 15,
    GET_COORDINATES: 16,

    MEASURE: 17
};