export const SensorValue = {
    NOT_SPECIFIED : 0,

    TEMPERATURE: 1,
    HUMIDITY: 2,
    LIGHT_INTENSITY: 3,
    IS_TILTED: 4,

    DISTANCE: 5,
    DISTANCE_FRONT: 6,
    DISTANCE_LEFT: 7,
    DISTANCE_RIGHT: 8
};